### PR TITLE
CF: Include new VA Caution Flags CSV in version generation #11354

### PR DESCRIPTION
**Pull request by zurbergram**
## Description
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11354

Switching to usage of a new CSV which results in the removal of code related to the following CSVs, tables to be dropped in a separate PR after this one is merged in.
- Settlement
- SchoolClosure
- Sec702School

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Comment by f1337** [comment]
There are several complex changes in this PR. I'm finding it difficult to keep track of contexts. To ensure a timely and thorough review, could we please either break this PR into multiple PRs, or reorganize the commits? Ideally Maybe group the changes by Settlement, SchoolClosure, and Sec702School? Or whatever logical grouping makes the most sense?

**Comment by zurbergram** [comment]
> There are several complex changes in this PR. I'm finding it difficult to keep track of contexts. To ensure a timely and thorough review, could we please either break this PR into multiple PRs, or reorganize the commits? Ideally Maybe group the changes by Settlement, SchoolClosure, and Sec702School? Or whatever logical grouping makes the most sense?

The PR is replacing the usages of Settlement, SchoolClosure, and Sec702School with VA Caution Flags. Additional changes are removing usage of wongi-engine that was "mapping" values.  This mapping was the original implementation and has since been determined to not be how the data should be handled. 


Changes are as such
- Remove usage of `rules` and `caution_flag_rules` tables
    - This is in the `db/seeds` files being changed and removed
    - In `institution_builder` methods `add_accreditation`, `add_mou`, `add_sec_702`, and `add_hcm`: it is mostly cleanup and switching to calling new way of creating `caution_flags`
        - `add_settlement` is a special case because it uses data from `va_caution_flags` instead of hardcoded values
    - In `caution_flag`: removing old wongi-engine mapping and replacing with a simple SQL insert statement that uses `caution_flag_template`s to determine values
    - Create the `caution_flag_template` classes for use in the simple SQL insert statements

- Remove usage of `sec702_schools`, `school_closures`, and `settlements` tables
    - This is in `institution_builder` and `csv_type`
- Use `va_caution_flags` in `institution_builder` ("generate" process)
    - This is in `institution_builder`, `csv_type`, and `caution_flag`
    - In `institution_builder`:
        - `add_sec_702`: Fix SQL logic to correctly select `sec_702` value for an institution from either `va_caution_flags` or `sec_702`
        - `add_school_closure`: Switch to `va_caution_flags`, since the date column in `va_caution_flags` is a varchar need to convert to a date
        - `add_settlement`: Switch to `va_caution_flags` and create `caution_flags` based off of values in `va_caution_flags`

**Comment by f1337** [comment]
~Thank you for the additional context! With ~2,000 lines changed, and the complexity of these changes, it would really help expedite review if this PR were broken up, or its commits reorganized, into the 3 changesets described.~

~If we cannot reorganize the PR, please allow more than 24 hours for review. Thank you!~

Please accept my apologies: I just learned that we are supposed to rubber-stamp these PRs without review, so no worries!

**Review by f1337 — APPROVED** [review]

**Review by sonntag-adam — APPROVED** [review]

**Pull request merged**
