### PR TITLE
Added approval status migrations

### PR DESCRIPTION
**Pull request by maneshkommidi**
https://github.com/department-of-veterans-affairs/gibct-data-service/issues/314

### CODE REVIEW

**Review by patrickvinograd — CHANGES_REQUESTED** [review]
Overall this looks okay, but I think you need to think through the roll-out of this. As soon as you deploy, the institutions controller will start trying to filter on `approval_status`, but that won't exist in the database right away, because migrations aren't run strictly in sync with code getting deployed. So API requests would probably start breaking. 

Similarly even if the column is in the database, it won't be populated until somebody goes into the tool and creates a new version from the data. So this may need to be broken out into a few phases to get the data into place before using it.

**Comment by wyattwalter** [comment]
@maneshkommidi that's exactly how we roll out features that need migrations. Db schema stuff goes into a PR, goes out and migrations run, then you can add the functionality that depends upon it.

**Comment by maneshkommidi** [comment]
@wyattwalter Thanks, updated the PR, will add the filter logic once after the new version of data is ready.

**Review by patrickvinograd — APPROVED** [review]

**Comment by patrickvinograd** [comment]
Looks good, sorry for the delay.

**Comment by patrickvinograd** [comment]
I think there will actually need to be *three* phases:
1) this migration
2) code change to populate the approved status in both these tables
(followed by a publishing a new version of the data in each environment)
3) code change to start filtering based on the approved status.

**Comment by maneshkommidi** [comment]
Yes @patrickvinograd we will address this in the same way.

**Pull request merged**
