### PR TITLE
Initial revision of training document

### PR DESCRIPTION
**Pull request by mphprogrammer**

### CODE REVIEW

**Comment by saneshark** [comment]
Fixes: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2057

**Comment by saneshark** [comment]
@mphprogrammer what's the status of this one?

**Comment by mphprogrammer** [comment]
This is waiting for review ...

**Comment by saneshark** [comment]
@mphprogrammer please take a look at Patrick's revision and make comments there in his PR. I think I agree with his revision notes.

**Comment by patrickvinograd** [comment]
Closing in favor of #278.

**Pull request closed without merging**
