### PR TITLE
Adding Additional DataPoints Migrations

### PR DESCRIPTION
**Pull request by maneshkommidi**

### CODE REVIEW

**Comment by maneshkommidi** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/issues/313

**Comment by jkassemi** [comment]
@maneshkommidi - is this just a PR for the migration, or are you planning on hooking this up to the data source?

**Comment by maneshkommidi** [comment]
@jkassemi This is just for a migration, will create separate PR for datasource.

**Review by jkassemi — APPROVED** [review]
Thanks, @maneshkommidi - straightforward, looks good to me.

For the commit message body for the squash merge, can you describe briefly what data will be stored in each field? (this doesn't need to be extensive, something like the human readable labels provided in https://github.com/department-of-veterans-affairs/gibct-data-service/issues/313#issue-313608609 would probably suffice).

**Comment by maneshkommidi** [comment]
In **f1sysnam** field **School system name** will be stored
In **f1syscod** field **School system code** will be stored
In **ialias** field **Alias** will be stored

**Pull request merged**
