### PR TITLE
Updating GI Bill CT Constants (Push on Aug 1st)

### PR DESCRIPTION
**Pull request by saintsoup52**
The Post-9/11 GI Bill rates increase every year on August 1st. This updates those rates for upcoming school year.

http://www.benefits.va.gov/GIBILL/resources/benefits_resources/rates/ch33/ch33rates080117.asp

### CODE REVIEW

**Comment by saintsoup52** [comment]
Sorry to pester but we need to push these new GI Bill rates ASAP. 

Many of the benefits for the Post-9/11 GI Bill go up on August 1st and I have heard that EDU has been getting complaints from students/schools.

@mphprogrammer @leannammiller @melwoodard

**Review by mphprogrammer — APPROVED** [review]
LGTM - Was someone assigned as a reviewer when this was opened?

**Comment by mphprogrammer** [comment]
@saintsoup52 Sorry about the delay, I don't remember this PR even being here !

**Comment by mphprogrammer** [comment]
@saintsoup52 @leannammiller The branch name has a colon (:), which is illegal. I think that is behind this issue of the checks not running ... I am going to make the changes manually and put up in another branch. I can't seem to pull the branch down because of this.

**Comment by mphprogrammer** [comment]
@saintsoup52 @leannammiller what (prescription) drugs am I on? This is a forked branch! @saintsoup52 you shouldn't have to fork this repo to make changes ...

**Comment by mphprogrammer** [comment]
@saintsoup52 We cannot merge a forked branch (probably for security) I am going to copy your changes and ping you for review.

**Pull request closed without merging**
