### PR TITLE
improved UI

### PR DESCRIPTION
**Pull request by saneshark**

### CODE REVIEW

**Review by mphprogrammer — DISMISSED** [review]
LGTM - with the exception of gibct_link

**Review by mphprogrammer — COMMENTED** [review]
LGTM - with the exception of gibct_link

**Review by mphprogrammer — COMMENTED** [review]
LGTM with the exception of gibct_link

**Review by mphprogrammer — APPROVED** [review]
LGTM

**Comment by saneshark** [comment]
@patrickvinograd I merged with one review, but this late in the game probably best to get your eyes on it as well. Had to merge though to unblock @U-DON

**Pull request merged**
