### PR TITLE
Add Zipcode Rate Archiving

### PR DESCRIPTION
**Pull request by devin-mccurdy**
Moved archiving functionality from `InstitutionsArchive` to `Archiver` so that it can be used by any model that is created when a new version is created.

Added archiving of `zipcode_rates` records.

Database migration PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/440

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19681

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by zurbergram — APPROVED** [review]
LGTM

**Review by delli-gatti-michael — APPROVED** [review]
Approved by QA

**Review by jholton — APPROVED** [review]
LGTM

**Pull request merged**
