### PR TITLE
Add rubyzip

### PR DESCRIPTION
**Pull request by zurbergram**
## Description

Adding https://github.com/rubyzip/rubyzip in support of https://github.com/department-of-veterans-affairs/va.gov-team/issues/15630

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by ericboehs — COMMENTED** [review]
This looks fine but I had a couple questions:

How does this add functionality to the current app? It doesn't look like it does and I assume future work will be done which will take advantage of it.

Is there a reason not to include it in the PR which will add the functionality?

**Comment by zurbergram** [comment]
> This looks fine but I had a couple questions:
> 
> How does this add functionality to the current app? It doesn't look like it does and assume future work will be done which will take advantage of it.
> 
> Is there a reason not to include it in the PR which will add the functionality?

This is adding the Gem for https://github.com/department-of-veterans-affairs/gibct-data-service/pull/764

It has been standard practice in this repo to separate adding Gems from the PRs that will use them so as to more easily identify when a gem was added

**Comment by ericboehs** [comment]
I can definitely approve but I think why a gem was added is a more important context. Adding the gem separate from the code requires sleuthing in GitHub instead of simply looking at a git diff/message.

I just wanted to bring attention to this norm and make sure we had a good reason to ignore it.

**Review by ericboehs — APPROVED** [review]

**Pull request merged**
