### PR TITLE
Bah message spies cop

### PR DESCRIPTION
**Pull request by ksantiagoBAH**
## Description
Update various files to pass `messageSpies` cop

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19828

## Testing done
Ran `bundle exec rake ci` to confirm no rubucop offenses are generated. 

## Acceptance criteria
- [x] No errors thrown when running `bundle exec rake ci`

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by sonntag-adam — APPROVED** [review]

**Comment by jholton** [comment]
Not sure why, but this PR is showing changes that are already in `master` under the 'Files Changed' tab.  Maybe a rebase would help?

**Comment by ksantiagoBAH** [comment]
> Not sure why, but this PR is showing changes that are already in `master` under the 'Files Changed' tab. Maybe a rebase would help?

I had to merge in the PRs for LeakyConstants and InHooks to this PR and it added all the extra files when I pulled from master.

**Comment by jholton** [comment]
Yeah, but why (for example) is the `InstitutionProgramsController` showing up in the diff?  That was merged into master yesterday.  Therefore there should be no diff.

Note: you also have a conflict to fix in `.rubocop_todo.yml`

**Comment by ksantiagoBAH** [comment]
Changed and PR  as other files were included that shouldn't of been. 

https://github.com/department-of-veterans-affairs/gibct-data-service/pull/484

**Pull request closed without merging**
