### PR TITLE
Updated rexml gem to 2.3.5

### PR DESCRIPTION
**Pull request by ksantiagoBAH**
## Description
Updated rexml gem from 2.3.4 to 2.3.5
## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Testing done
local

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by rileyanderson — CHANGES_REQUESTED** [review]
~This has breaking changes to login that need to be addressed before we update this. This gem was previously updated but had to be reverted back.~

**Comment by shawkey-daniel** [comment]
@rileyanderson We tested in GIDS and it does not appear to affect login for GIDS.

**Comment by rileyanderson** [comment]
@shawkey-daniel yes I just realized that. I thought I was looking at vets-api. Carry on!

**Review by rileyanderson — APPROVED** [review]

**Pull request merged**
