### PR TITLE
Facility map duplicate institutions fix

### PR DESCRIPTION
**Pull request by devin-mccurdy**
The recursive facility map queries are correctly using the institution version, but they return facility codes which are then used without correctly using the version number.

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19636

### CODE REVIEW

**Review by zurbergram — APPROVED** [review]
LGTM

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by delli-gatti-michael — APPROVED** [review]
Approved by QA

**Review by jholton — APPROVED** [review]
LGTM

**Review by omgitsbillryan — APPROVED** [review]

**Pull request merged**
