### PR TITLE
allow searching for address in School Autocomplete widget api

### PR DESCRIPTION
**Pull request by lihanli**
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11469
modifies autocomplete api to allow an optional `include_address` param which will use the search term to query address fields

### CODE REVIEW

**Comment by saintsoup52** [comment]
This is exciting... How will this new search pattern work exactly?

Any way we could have an advance search function? Instead of searching by name, search by state or zip code.

**Comment by lihanli** [comment]
this api will be used by the gi bill complaint tool to look up schools by name or address
we could modify it to search by state or zip code, @rtluu is my product manager, you can talk to him about feature suggestions

**Comment by saintsoup52** [comment]
Thank you for the explanation... I just don't know why anyone would look up a school by address (vs state or zip).

**Review by jholton — APPROVED** [review]
LGTM

**Pull request closed without merging**
