### PR TITLE
Fixed lowercase ojt in API. Fixes #226

### LINKED ISSUE #226: facets method in the institution controller relies on lower case 'ojt'
Need to implement a quick fix to change hard coded 'ojt' to upper cased 'OJT'

### PR DESCRIPTION
**Pull request by mphprogrammer**

### CODE REVIEW

**Review by saneshark — APPROVED** [review]
LGTM

**Comment by patrickvinograd** [comment]
I'm not clear on what the issue is that this is supposed to fix. In fact it seems like it breaks the "employer" count - I pulled down your branch and ran it locally, and the employer count shows as zero when ojt count = 71. On dev-api right now (without this change), the employer count matches the ojt count.

**Review by patrickvinograd — DISMISSED** [review]
Please respond to my question because this seems broken at least when I run it locally.

**Comment by patrickvinograd** [comment]
I guess it would be helpful to know - how is the institution type of "OJT" intended to be represented (uppercase. vs. lowercase) in:
1. the input CSV
2. the database
3. the Institution model
4. the API result for an individual institution
5. the API facets object

**Comment by patrickvinograd** [comment]
Also even if this is the right fix, could presumably reference `Institution::EMPLOYER` instead of re-defining the magic string in the controller.

**Comment by patrickvinograd** [comment]
Ok, I dropped and re-seeded the database on my machine and now I see the types are uniformly in uppercase, so this change makes sense. 

I can re-seed the dev and staging environments - but I need a heads up about when I should do that as its not standard procedure on any given redeployment.

**Comment by mphprogrammer** [comment]
Patrick - Forgot completely about Institution::Employer, and I am that put that in last year ...

**Comment by mphprogrammer** [comment]
@patrickvinograd In all those cases - facility code, institution, country, state, institution type should be in upper case ... It is that way in the DB - as a general policy we should store the data as it is required for reporting purposes, and not for display.

**Comment by mphprogrammer** [comment]
@patrickvinograd replaced the controller constant with Institution::EMPLOYER. Could you give it the once over, and if OK - merge?

**Pull request merged**
