### PR TITLE
Ruby 2.5.7

### PR DESCRIPTION
**Pull request by zurbergram**
## Description
As a developer, I need to upgrade GIDS to Ruby v.2.5.7 so that I can upgrade ruby to the most recent version.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/5746

## Testing done
- smoke test application

## Acceptance criteria
- [ ] GIDS Ruby is on version 2.5.7.
- [ ] The Readme for the GIDS Repository is updated to reflect version 2.5.7 of Ruby

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

## Dependencies
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/582

### CODE REVIEW

**Comment by zurbergram** [comment]
```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Style/HashEachMethods
 - Style/HashTransformKeys
 - Style/HashTransformValues
```
https://rubocop.readthedocs.io/en/latest/cops_style/#stylehasheachmethods
https://rubocop.readthedocs.io/en/latest/cops_style/#stylehashtransformkeys
https://rubocop.readthedocs.io/en/latest/cops_style/#stylehashtransformvalues

**Comment by zurbergram** [comment]
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Layout/SpaceAroundMethodCallOperator (0.82)
 - Lint/RaiseException (0.81)
 - Lint/StructNewOverride (0.81)
 - Style/ExponentialNotation (0.82)
For more information: https://docs.rubocop.org/en/latest/versioning/

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by LindseySaari — APPROVED** [review]
👍

**Review by sonntag-adam — APPROVED** [review]

**Pull request merged**
