### PR TITLE
Adding sample constants to seeds.rb

### PR DESCRIPTION
**Pull request by ben-USDS-damman**
These are the current values sourced from production.

### CODE REVIEW

**Comment by saneshark** [comment]
@ben-USDS-damman since this is just an update to the constants, I'm going to give it the LGTM, and we can try to address the code coverage issues separately in a different PR.

**Review by saneshark — APPROVED** [review]
approving. OK to merge despite failing travis (it's failing for code coverage only).

**Comment by saintsoup52** [comment]
Sorry for the dumb question... does this mean we will be able to update the constants on the GI Bill CT the same way we update the data on the tool?

Because that would be awesome sauce!

**Comment by ben-USDS-damman** [comment]
@saintsoup52 Yes, that's the general idea. 💯

**Pull request merged**
