### PR TITLE
[WIP] SAML integration

### PR DESCRIPTION
**Pull request by patrickvinograd**

### CODE REVIEW

**Comment by wyattwalter** [comment]
@patrickvinograd I think we can close this PR and delete branch at this point?

**Comment by wyattwalter** [comment]
Ohh... it looks like https://github.com/department-of-veterans-affairs/gibct-data-service/pull/318 is using the same branch name. We definitely want to hold off on deleting the branch until that's done as I'm unsure how git / GitHub would respond to that.

**Comment by jkassemi** [comment]
@adi-pen does your work supersede this?

**Comment by adi-pen** [comment]
@jkassemi Yeah. This PR can be closed.

**Pull request closed without merging**
