### PR TITLE
added rake task to update constants

### PR DESCRIPTION
**Pull request by mphprogrammer**
Broke out 02_data.rb from seeds into 02_constants and 03_data.
Added rake task db:update_constants to update constants table from console.

### CODE REVIEW

**Comment by saintsoup52** [comment]
What does this do exactly? Aside from make the magic happen?

**Comment by saneshark** [comment]
@saintsoup52 it allows us to update a table that stores the constants from a database seed file. The database seed file is typically used for building the table when the database is empty. What Marc has done here is made it such that, you can modify part of the database seed, and call a rake task to update only the constants.

**Comment by mphprogrammer** [comment]
@saintsoup52 The latest version of GIBCT was written to draw the calculator constants from GIDS and those values were loaded in the database from a "seeds" file that runs once. Because the constants live in a table, simply changing the "seeds" won't change the data, because it really only runs once in production to initially populate the tables. This rake task can be run from the command line on the server, and it will populate the constants table with your changes.

**Review by saneshark — APPROVED** [review]
@mphprogrammer can we test this on dev/staging to make sure it works as expected before trying it on production? Should it be run during off-peak?

**Comment by saintsoup52** [comment]
Thanks for the explanation!

Probably would be easier in the future to make the constants just another file that we can upload and update without having to do any coding/raking.

**Comment by mphprogrammer** [comment]
I, having the brain of a dehydrated tardigrade, forgot that it was the seeds file we changed.

@saneshark yes, I can ask James to try it on the staging server first to make sure all is ok. And then have him do it in production if it works. There are only 23 rows that will be changed.

**Comment by mphprogrammer** [comment]
Actually, the CSV metaphor for Constants would be a simple thing to do.

**Pull request merged**
