### PR TITLE
Support new weams.csv

### PR DESCRIPTION
**Pull request by saneshark**
Fixes: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11687

Need to manually diff and verify that the new weam.csv doesn't introduce issues since the specs had to be altered to support this.

### CODE REVIEW

**Comment by saneshark** [comment]
@jkassemi Note the this new weams.csv makes a major departure from the old weams.csv, the columns were not merely added, they've been re-ordered and re-named. In particular, "Accredited" is no longer near the end of the line. It is in the middle after institution country. Other than that, it mostly just looks like they down-cased column headers.

**OLD Columns**
Facility Code,Institution Name,Address 1,Address 2,Address 3,Institution City,Institution State,Institution Zip Code,Institution Country,Current Academic Year BAH Rate,Principles of Excellence,Current Academic Year Yellow Ribbon,POO Status,Applicable Law Code,Institution of Higher Learning Indicator,OJT Indicator,Correspondence Indicator,Flight Indicator,Non-College Degree Indicator,IPEDS,OPE,Accredited

**NEW Columns**
facility code,institution name,address 1,address 2,address 3,institution city,institution state,institution zip code,institution country,accredited,current academic year bah rate,principles of excellence,current academic year yellow ribbon,poo status,applicable law code,institution of higher learning indicator,ojt indicator,correspondence indicator,flight indicator,non-college degree indicator,ipeds,ope,priority enrollment,independent study

Is this going to present a problem?

**Comment by saintsoup52** [comment]
Not sure if it matters... but I think accreditted was never the last column in WEAMS in the old version of the data.

**Review by jkassemi — APPROVED** [review]

**Comment by saintsoup52** [comment]
We don't use the OPE field from the WEAMS file. We only use the OPE field from the crosswalk file.

Hope that helps.

**Comment by saneshark** [comment]
I can confirm that I was able to build the institution table with this new weams file without issues. Merging.

**Pull request merged**
