### PR TITLE
create sec103 table

### PR DESCRIPTION
**Pull request by hughes-dustin**
## Description
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6852

DB changes for 6852. 

## Testing done
Migrated db changes and confirmed table was created. 

## Acceptance criteria
- [x] sec103 table is created. 
- [x] sec103 columns added to institutions table
- [x] sec103 columns added to institutions_archives table

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — CHANGES_REQUESTED** [review]
Leave name in there for original fidelity even though it is redundant.

**Comment by hughes-dustin** [comment]
> Facility name is redundant in the sec103s table. I'll modify the AC to not require the name field.

Will that mean the csv will not include `facility name` as well?

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by delli-gatti-michael — APPROVED** [review]

**Review by sonntag-adam — APPROVED** [review]

**Review by johnpaulashenfelter — APPROVED** [review]
👍

**Pull request merged**
