### PR TITLE
PRs #381, #389, #391 in single branch

### PR DESCRIPTION
**Pull request by zurbergram**
## Description

Combing PRs/branches below into a single PR to reduce code conflict issues

- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/381
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/389
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/391
- branch `bah-colmery-107`

## Testing
Smoke tested by 
- blowing away existing database
- recreating database
- migration on database
- seeding database
- exporting weams.csv to verify columns
- exporting institutions.csv to verify columns

### CODE REVIEW

**Review by ksantiagoBAH — APPROVED** [review]
LGTM

**Review by elder-joseph — APPROVED** [review]

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Comment by zurbergram** [comment]
@department-of-veterans-affairs/backend-review-group Could I get a code review on this at your earliest convenience. Thank you!

**Review by annaswims — CHANGES_REQUESTED** [review]
Please take a look at the PR guidelines in https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Code%20Review%20Norms.md#what-makes-a-good-code-review-pull-request and https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Writing_Small_PRs.md . This PR is too large and is asking us to re-review code we've already reviewed, mixed with new code.

**Pull request closed without merging**
