### PR TITLE
Change build/push methods to POST

### PR DESCRIPTION
**Pull request by patrickvinograd**
Fixes https://github.com/department-of-veterans-affairs/gibct-data-service/issues/213

Open to differing opinions about HTTP method - POST vs. PUT. These operations are not very resource-oriented so it seemed like a toss-up.

### CODE REVIEW

**Comment by patrickvinograd** [comment]
Interestingly this did not cause any spec failures, even though the dashboards_controller spec does a `get :build` and a `get :push`. But maybe we'd need a request spec to exercise this distinction?

**Comment by patrickvinograd** [comment]
Yes, looks like only request specs exercise routing. Will add one after next block of meetings.

**Comment by saneshark** [comment]
@patrickvinograd I'm +1 for either request specs or routing specs. Both should help surface these type of issues in the future.

**Comment by saneshark** [comment]
Since we already have the controller specs, maybe routing specs would suffice, but replacing controller specs with request specs (which encapsulate controller and routing better), would probably be the better long term solution (though a little annoying to do when dealing with file upload).

**Review by saneshark — APPROVED** [review]
Feel free to open a separate issue to track improving specs if you wish. This LGTM though.

**Pull request merged**
