### PR TITLE
Add React Support Part 1

### PR DESCRIPTION
**Pull request by zurbergram**
## Description
Part of https://github.com/department-of-veterans-affairs/gibct-data-service/pull/471/
- add gems react-rails and webpacker
- `bundle exec rails webpacker:install`
    - This was needed as after installing the 2 gems deploy was looking for `config/webpacker.yml` and would fail if file was not found
- ignore `node_modules` directory when running rubocop

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19826

A a developer I need to add the React library to GIDS so that it has the ability to use the same tech stack as the Comparison Tool.

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Comment by jholton** [comment]
I've never used this setup, so I don't have strong opinions.
Looks like this is just gem installs and generated boilerplate.
A couple questions:
* Can the server(s) (webpack and Rails) be started up in this state?
* Do we need the `packs/application.js` file?  Is it just an example file generated by the webpacker install?

**Comment by zurbergram** [comment]
> I've never used this setup, so I don't have strong opinions.
> Looks like this is just gem installs and generated boilerplate.
> A couple questions:
> 
> * Can the server(s) (webpack and Rails) be started up in this state?
> * Do we need the `packs/application.js` file?  Is it just an example file generated by the webpacker install?

The application starts up and runs in this state

When I do the `bundle exec rails generate react:install` step in another PR of https://github.com/reactjs/react-rails#rails-5x it will modify `app/javascript/packs/application.js` to bring in React for us

**Comment by kfrz** [comment]
@zurbergram can you expound a bit upon why the `react` dependency is necessary? What exactly is blocked from happening that requires adding such a heavy dependency? I'm just trying to understand the problem statement more fully, links to more issues are a reasonable response.

**Comment by zurbergram** [comment]
> @zurbergram can you expound a bit upon why the `react` dependency is necessary? What exactly is blocked from happening that requires adding such a heavy dependency? I'm just trying to understand the problem statement more fully, links to more issues are a reasonable response.

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19826 is the originating issue 
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/471 is the original PR
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19873 is the epic for this body of work

**Comment by kfrz** [comment]
Those issues don't really explain why `react` was decided upon, my worry is adding a heavy dependency for something that may be better suited to rails built in views?

**Comment by shawkey-daniel** [comment]
> Those issues don't really explain why `react` was decided upon, my worry is adding a heavy dependency for something that may be better suited to rails built in views?

The GIDS UI provides a tool for administrators to upload and manage data for the GI Bill Comparison Tool (GIBCT). The UI is only utilized by a couple of admin users, so performance is not really an issue. There are several stories in the backlog to enhance the functionality of the GIDS UI to facilitate data maintenance. The team working the development stories also maintains the GIBCT utilizing React. Adding React to the GIDS UI will allow the team rapidly develop enhanced functionality for the GIDS UI working with familiar tools and not having to switch tool context when switching to GIDS UI.

**Pull request closed without merging**
