### PR TITLE
getting test coverage to 100%

### PR DESCRIPTION
**Pull request by saneshark**

### CODE REVIEW

**Comment by saneshark** [comment]
NOTE: this fixes https://github.com/department-of-veterans-affairs/vets.gov-team/issues/957

**Comment by ben-USDS-damman** [comment]
LGTM although my local environment is failing on a handful of ope6 related fields. Probably something out of join on my machine, though.

**Review by ben-USDS-damman — APPROVED** [review]

**Comment by saneshark** [comment]
@ben-USDS-damman I did notice that when I dropped my db, did a create, migrate, and seed... that my schema did not match up with what is in master 100%. And I don't mean just whitespace and stuff shuffled around. I think maybe if you do those steps and checkin your changes for schema.rb you might be in good shape. Maybe someone made some changes forgot to check them in?

**Comment by mphprogrammer** [comment]
LGTM.

**Pull request merged**
