### PR TITLE
Update puma and nokogiri

### PR DESCRIPTION
**Pull request by devin-mccurdy**
## Description
Updated puma and nokogiri to resolve security vulnerabilities

- https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-7rrm-v45f-jp64
- https://github.com/puma/puma/security/advisories/GHSA-q28m-8xjw-8vr5

## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Testing done
Tested locally

## Screenshots
N/A

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Comment by devin-mccurdy** [comment]
I keep forgetting about dependabot!

**Comment by zurbergram** [comment]
See https://github.com/department-of-veterans-affairs/gibct-data-service/pull/825

**Comment by devin-mccurdy** [comment]
THILTON GOT US COVERED

**Pull request closed without merging**
