### PR TITLE
Fixed the IPEDS Issue

### PR DESCRIPTION
**Pull request by maneshkommidi**

### CODE REVIEW

**Comment by jkassemi** [comment]
Thanks @maneshkommidi - can you reference the source ticket/or describe the issue that's being addressed by this fix?

**Comment by maneshkommidi** [comment]
@jkassemi  https://github.com/department-of-veterans-affairs/gibct-data-service/issues/307

**Comment by jkassemi** [comment]
Update looks good. Can you work to address the build failure so we can get this merged and deployed?

**Comment by maneshkommidi** [comment]
@jkassemi I Cannot see why the build is failed, as I do not have access to Jenkins, can you please let me know the reason for the build failure so that I can work on that.

**Comment by jkassemi** [comment]
@maneshkommidi, can you provide any information about what functionality the leading zeros originally provided? Are they necessary for the IPEDS unit id, or have any affects on the CSV export functionality?

**Comment by maneshkommidi** [comment]
@jkassemi As per the https://github.com/department-of-veterans-affairs/gibct-data-service/issues/307 the zero's are not necessary for IPEDS unit id, I think it will not have a impact on CSV export functionality as we are using the cross converter only for IPEDS unit id converstion.

**Review by jkassemi — APPROVED** [review]

**Pull request merged**
