### PR TITLE
Updated column names

### PR DESCRIPTION
**Pull request by ksantiagoBAH**
## Description
As a developer, I need to update the GIDS tool to accept the new column names for the campus type and parent facility code so that the information can be displayed within the Comparison Tool

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19640

## Testing done
Local Testing

## Acceptance criteria
- [x] "Campus Type" header is replaced with "Campus indicator" header.
- [x] "Parent facility code id" header is replaced with "Parent facility code" header.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by zurbergram — APPROVED** [review]
LGTM

**Comment by ksantiagoBAH** [comment]
Also updated headers for Programs csv and School Certifying Officials csv

SCO:
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19451

programs:
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19448

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by sonntag-adam — APPROVED** [review]

**Review by jholton — APPROVED** [review]
LGTM

**Pull request merged**
