### PR TITLE
Docker-based CI

### PR DESCRIPTION
**Pull request by edpaget**
Everything else is using docker for CI, so this should too.

### CODE REVIEW

**Comment by wyattwalter** [comment]
`make clean` results in some changes picked up by git:

```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    log/.keep
```

**Review by wyattwalter — APPROVED** [review]
I adjusted the `make clean` task slightly to only modify the contents of `log/` rather than deleting it entirely to avoid issues with git and that task. Looks good to me!

**Comment by wyattwalter** [comment]
Noticed on the change after I approved it that we were not doing a `make clean` at the end and leaving Postgres containers around. Added that post task so we wouldn't do that.

**Comment by edpaget** [comment]
@maneshkommidi sorry this took so long to resolve, but once this is merged you'll need to merge master into your PR's branch and then it should work fine on Jenkins

**Comment by maneshkommidi** [comment]
@edpaget Sure will do, Thanks

**Pull request merged**
