### PR TITLE
VFEP-1431 - Rails upgrade to 7.1.3

### PR DESCRIPTION
**Pull request by GcioGregg**
## Description
VFEP-1431 - upgrade GIBCT from Rails 7.0.8 to 7.1.3

## Original issue(s)
[vfep-1431](https://jira.devops.va.gov/browse/VFEP1431)

## Testing done
Developer user testing - create new version, upload spreadsheets to dashboard, export spreadsheets from dashboard, generate reports, and GI Bill comparison tool all work. Rspec tests pass.

## Acceptance criteria
- [x] GIBCT dashboard & comparison tool work as expected.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by nfstern02 — CHANGES_REQUESTED** [review]
filter_parameter_logging.rb - add :password back into the list of filter_parameters. That's actually defined in the application and needs to be filtered. The other ones are added by Rails.

In a number of places single quotes are replaced by double quotes. Consider changing them back to reduce the false positives w/respect to changes identified. The rule of thumb is use single quotes unless string interpolation is needed.

search_geocoder_spec.rb not sure why that's wrapped in a block like that and the sleep may be needed.

**Comment by GcioGregg** [comment]
re: filter_parameter_logging.rb, password is effectively filtered since "passw" is filtered and "password" contains "passw".
re: double quotes, I can change them back, they were recommended by rails app:update
re: search_geocoder_spec.rb, it's wrapped because the test was failing due to the async job that was executing unpredictably and conflicting with the transactional state managed by the database cleaner.  The wrapper ensures this test runs within the test transaction and therefore won't conflict with the database cleaner.  The sleep does not appear to be needed any longer.

**Comment by nfstern02** [comment]
Couple of things. Please schedule a Code Review request with Ryan/Eric to get OCTO seal of approval. Also, I think we should push vfep1478 thru the system first.

**Comment by nfstern02** [comment]
The double quotes is not a recommendation, the author of the script just didn't bother to swap them out for single quotes.


From: Gregg P ***@***.***>
Sent: Monday, May 27, 2024 8:50 AM
To: department-of-veterans-affairs/gibct-data-service ***@***.***>
Cc: Stern, Noah F. (GovCIO LLC) ***@***.***>; Review requested ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/gibct-data-service] VFEP-1431 - Rails upgrade to 7.1.3 (PR #1133)


re: filter_parameter_logging.rb, password is effectively filtered since "passw" is filtered and "password" contains "passw".
re: double quotes, I can change them back, they were recommended by rails app:update
re: search_geocoder_spec.rb, it's wrapped because the test was failing due to the async job that was executing unpredictably and conflicting with the transactional state managed by the database cleaner. The wrapper ensures this test runs within the test transaction and therefore won't conflict with the database cleaner. The sleep does not appear to be needed any longer.

-

**Review by nfstern02 — APPROVED** [review]

**Comment by GcioGregg** [comment]
closing this PR, will create another

**Pull request closed without merging**
