### PR TITLE
Factory bot update

### PR DESCRIPTION
**Pull request by zurbergram**
## Description
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19788

https://thoughtbot.com/blog/deprecating-static-attributes-in-factory_bot-4-11

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by jholton — CHANGES_REQUESTED** [review]
This looks like it's mostly Rubocop changes.  Can we separate the Factory Bot upgrade from the Rubocop upgrade?  And then separate the Rubocop upgrades into manageable PRs? We recently did this in `vets-api`.  Check out [the latest Rubocop PRs](https://github.com/department-of-veterans-affairs/vets-api/pulls?utf8=%E2%9C%93&q=is%3Apr+rubocop) in that repo as examples.

**Comment by zurbergram** [comment]
> This looks like it's mostly Rubocop changes. Can we separate the Factory Bot upgrade from the Rubocop upgrade? And then separate the Rubocop upgrades into manageable PRs? We recently did this in `vets-api`. Check out [the latest Rubocop PRs](https://github.com/department-of-veterans-affairs/vets-api/pulls?utf8=%E2%9C%93&q=is%3Apr+rubocop) in that repo as examples.

The goal of this PR is too update FactoryBot however because of https://thoughtbot.com/blog/deprecating-static-attributes-in-factory_bot-4-11 a Rubocop update was done to easily fix the issue of deprecated static attributes in factories.

The `.rubocop.yml` now mirrors https://github.com/department-of-veterans-affairs/vets-api/blob/master/.rubocop.yml

All of the Rubocop changes are `--auto-correct` changes, none were manual fixes.

**Review by sonntag-adam — APPROVED** [review]

**Comment by jholton** [comment]
Ah, that makes sense.
This is still a lot for my brain to process, and I'd like to break them up.
Let's do the Rubocop upgrade first if that'll get rid of the deprecation warnings. Then do the Factory Bot upgrade.

The `vets-api` `.rubocop.yml` file is a good starting point, but shouldn't necessarily be considered ideal.
Specifically, the entries marked
> Determined to be too benign and/or numerous to justify changing    

should probably be revisited.

Here's what I'd like to see:
1. PR for Rubocop upgrade and autocorrect fixes based on the `.rubocop.yml` file in this PR
2. PR for the Factory Bot upgrade
3. Time permitting, PRs that revisit the 
> too benign and/or numerous to justify changing

entries, one per cop.

**Pull request closed without merging**
