### PR TITLE
add description column to calculator constants table

### PR DESCRIPTION
**Pull request by hughes-dustin**
## Description
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6163

The DB changes needed for story 6163.
## Acceptance criteria
- [x] description column is added to calculator_constants table
- [x] user can upload calculator_constant csv with descriptions

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by shawkey-daniel — APPROVED** [review]
LGTM

**Review by sonntag-adam — APPROVED** [review]

**Review by annaswims — CHANGES_REQUESTED** [review]
Please merge the migration in a separate pr prior to the code that depends on the migration and make sure that migration is run before this PR is merged.

**Comment by hughes-dustin** [comment]
> Please merge the migration in a separate pr prior to the code that depends on the migration and make sure that migration is run before this PR is merged.

CSV changes have been moved to [PR 600](https://github.com/department-of-veterans-affairs/gibct-data-service/pull/600).

**Review by annaswims — APPROVED** [review]
LGTM

**Pull request merged**
